### ISSUE TITLE
"The request did not succeed successfully." 500 (Server Error) at GET https:/<server url>/service/extension/rocket?action=signOn

### ISSUE THREAD

**Issue by skullchap** [jorgedlcruz/zimbra-zimlets#4]
Hi, Rocket.Chat Zimbra zimlet full integration does not work as expected. If i create new account at zimbra and then sign on, i get congratulation message that rocket.chat account is created and it does appear as new account at Rocket.Chat side. Credentials it provides also work in mobile applications. 

The problem is whenever i log in at zimbra it never logs in on rocket.chat side, rocket chat always throws "Please Log in" or "The request did not succeed successfully."

Chrome's inspect console throws 500 Server error at "GET https:/<server url>/service/extension/rocket?action=signOn"

I use zimbra 8.8.12 and latest Rocket.Chat snap version. Both servers signed with Let's Encrypt certificates.

**Comment by karvox** [comment]
Same problem! What is wrong?

![zimbra-rocket-chat](https://user-images.githubusercontent.com/7475131/76997537-36fc3100-6932-11ea-9947-707b7ae66e11.png)

**Comment by ishtarmms** [comment]
Hi, I have same issue for few days.

If I use Firefox,  I saw massage as "not allow Firefox to display the page if another site has embedded it RocketChat" 

So I login to Rocket Chat. 

Going to "Administration -> General -> X-Frame-Options", delete "sameorigin" and save.

I use Zimbra 8.8.15 and Rocket.Chat 3.5.2 version.
